######################################################################
# Automatically generated by qmake (2.01a) ven. 24. juin 19:36:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . resources src
INCLUDEPATH += .
CONFIG += qwt qxt console

# Input
HEADERS += src/HospitApp.hpp
SOURCES += src/HospitApp.cpp src/main.cpp
RESOURCES += resources/resources.qrc
